# 1 | Sprint 9
RuslanBoo/java-filmorate pull request #1
Opened 2022-10-28 17:08 UTC by RuslanBoo

Спринт 9 | Финальное ТЗ 1

2022-10-29 13:14 UTC, afomkina commented on .gitignore
> -*.class
А зачем ты удалил файл .gitignore?
Он нужен для того, чтобы в гит не заливались лишние файлы, например, настройки ide или файлы билда.
Чуть ниже есть два файла `.DS_Store`, они нам не нужны в репозитории, нужно их убрать

2022-10-29 13:14 UTC, afomkina commented on src/main/java/filmorate/utils/validators/ReleaseDate.java
> +public @interface ReleaseDate {
Клево, что создал сою собственную аннотацию и валидатор - молодец 👍

2022-10-29 13:14 UTC, afomkina commented on src/main/java/filmorate/utils/validators/ReleaseDate.java
> +class DateReleaseValidator implements ConstraintValidator<ReleaseDate, Temporal> {
Лучше вынести в отдельный файл. В коммерческой разработке принято хранить все классы по разным файлам, так их удобнее переиспользовать и проще читать код

2022-10-29 13:14 UTC, afomkina commented on src/main/java/filmorate/controller/FilmController.java
> +import org.springframework.web.bind.annotation.*;
_Саморазвитие_
В коммерческой разработке не принято использовать _wildcard_ в импортах.
Вот отличная [статья](https://struchkov.dev/blog/using-wildcard-imports-in-java/) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2022-10-29 13:14 UTC, afomkina commented on src/main/java/filmorate/model/Film.java
> +    private int id;
Лучше добавлять пустую строку после каждой переменной, если над ней стоит аннотация - так становится проще визуально воспринимать код

2022-10-29 13:14 UTC, afomkina commented on pom.xml
> +	<description>Filmorate app for Practicum</description>
_Опционально_
Лучше в описании кратко рассказать, что делает проект

2022-10-29 13:14 UTC, AnastasiyaFomkina commented on src/main/java/filmorate/controller/FilmController.java
> +        return film;
Лучше возвращать объект, который возвращает метод _create_. Так мы сократим код и избавимся от дублирования - получится одна строка

2022-10-29 13:14 UTC, AnastasiyaFomkina commented on src/main/java/filmorate/controller/FilmController.java
> +        filmStorage.update(film);
Здесь тоже лучше использовать возвращаемый объект метода

2022-10-29 13:14 UTC, AnastasiyaFomkina commented on src/main/java/filmorate/controller/UserController.java
> +        return user;
И в этом классе, лучше возвращать объект, который возвращают методы `create` и `update`

2022-10-29 13:14 UTC, AnastasiyaFomkina commented on src/main/java/filmorate/utils/storage/UserStorage.java
> +@Slf4j
Не хватает отступа после импорта, поправь, пожалуйста, весь проект по code-style:
[Ctrl+Alt+L](https://blog.jetbrains.com/idea/2020/03/top-15-intellij-idea-shortcuts/#:~:text=next%20need%20it.-,%E2%8C%A5%E2%8C%98L%20or%20Ctrl%2BAlt%2BL,-We%20can%20easily)

2022-10-29 13:14 UTC, AnastasiyaFomkina commented on src/main/java/filmorate/utils/storage/StorageManager.java
> +public interface StorageManager <T>{
🔥

2022-10-29 13:14 UTC, AnastasiyaFomkina commented on src/main/java/filmorate/model/User.java
> +        this.name = name == null ? login : name;
`name` может прийти пустой строкой и тогда вместо имени не проставится логин.
 Нужно доработать этот момент

2022-10-29 13:14 UTC, AnastasiyaFomkina commented on src/main/java/filmorate/model/User.java
> +        this.name = name == null ? login : name;
https://disk.yandex.ru/i/Lt7xHVNMI55AmQ

2022-10-29 13:14 UTC, AnastasiyaFomkina commented on src/main/java/filmorate/utils/storage/FilmStorage.java
> +        log.debug("Обновлен фильм: {}", film);
Логирование - это очень удобно, молодец 👍

2022-10-29 15:45 UTC, RuslanBoo commented on src/main/java/filmorate/controller/FilmController.java
> +import org.springframework.web.bind.annotation.*;
Спасибо! Поменял настройки в IDEA 👍

2022-10-29 15:46 UTC, RuslanBoo commented on src/main/java/filmorate/model/Film.java
> +    private int id;
Исправил

2022-10-29 19:40 UTC, AnastasiyaFomkina requested changes
Отписалась в ревьюэлке:)

2022-10-30 12:55 UTC, AnastasiyaFomkina approved these changes

2022-11-08 16:12 UTC, merged